# Generated by Django 3.2 on 2021-04-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_skill', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=500)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.typeskill')),
            ],
        ),
    ]
