"""empty message

Revision ID: 2c394fd300fe
Revises: 
Create Date: 2021-04-27 20:24:33.060761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c394fd300fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_skill', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('fk_id_type_skill', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_id_type_skill'], ['type_skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_id_user_group', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fk_id_user_group'], ['user_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('answer__user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_id_user', sa.Integer(), nullable=False),
    sa.Column('fk_id_question', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['fk_id_question'], ['question.id'], ),
    sa.ForeignKeyConstraint(['fk_id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer__user')
    op.drop_table('user')
    op.drop_table('question')
    op.drop_table('user_groups')
    op.drop_table('type_skill')
    # ### end Alembic commands ###
